### ISSUE TITLE
Could not find a declaration file for module 'react-native-paper'

### ISSUE THREAD

**Issue by iM-GeeKy** [callstack/react-native-paper#3730] opened 2023-03-06 21:21 UTC
### Current behaviour

As of `5.3.0`, imports from `react-native-paper` are throwing typescript errors saying `Could not find a declaration file for module 'react-native-paper'.`.

### Expected behaviour

The imports should be resolved as usual.

### How to reproduce?

https://github.com/iM-GeeKy/paper-5.3.0-bug

### Preview

![Group 601](https://user-images.githubusercontent.com/7604441/223233659-b3625be5-3911-4522-b08f-0a9535ef4630.png)

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 16.2
| android                        | x
| react-native                | 0.70.5 and 0.71.3
| react-native-paper    | 5.3.0
| node                            | 16.16.0
| npm or yarn                | yarn
| expo sdk                     | ^47.0.0 and ^48.0.5

**Comment by BSekula** [comment] 2023-03-06 22:22
Looks like the issue is wrong path in [package.json](https://github.com/BSekula/react-native-paper/blob/main/package.json#L9)

Should be:

```
"types": "lib/typescript/src/index.d.ts",
```

**Comment by lukewalczak** [comment] 2023-03-06 22:42
Fixed via: https://github.com/callstack/react-native-paper/commit/9d0aee1f7e37958e343a535b3ebd5ad093def255

Thanks @iM-GeeKy and @BSekula! I've just release patch version `5.3.1`, try it and let me know if everything works 🙌🏽

**Closed by lukewalczak** 2023-03-06 22:42 UTC
Labels: bug

**Comment by iM-GeeKy** [comment] 2023-03-06 23:21
> Fixed via: [9d0aee1](https://github.com/callstack/react-native-paper/commit/9d0aee1f7e37958e343a535b3ebd5ad093def255)
> 
> Thanks @iM-GeeKy and @BSekula! I've just released patch version `5.3.1`, try it and let me know if everything works 🙌🏽

Everything is working on my end. I appreciate the quick turnaround!
