### ISSUE TITLE
While running in iOS device, the List.Accordion List indicator is coming with different icons(not up and down arrow).

### ISSUE THREAD

**Issue by AmitPandya007** [callstack/react-native-paper#1265] opened 2019-08-03 06:14 UTC

**Comment by jaysbytes** [comment] 2019-08-26 11:56
Can you attach any screenshot or code to debug (preferably on https://snack.expo.io)

**Comment by jaysbytes** [comment] 2019-08-26 11:58
closing, duplicate of #1266

**Closed by jaysbytes** 2019-08-26 11:58 UTC
