### ISSUE TITLE
Drawer have the functionality of "tapToClose"?

### ISSUE THREAD

**Issue by eduardobarbiero** [callstack/react-native-paper#732] opened 2019-01-17 02:29 UTC
My drawer is not closing when clicking somewhere outside the drawer's area, does anyone have any idea what it might be?

Using lastest version.

**Comment by ferrannp** [comment] 2019-01-17 11:22
Can you post a snack?  We don't really have a `Drawer` component in Paper.

**Comment by eduardobarbiero** [comment] 2019-01-17 11:58
In this snack, Drawer closing on tap, but where is this setting? :O
[Example React Native Paper Snack](https://snack.expo.io/@satya164/github.com-callstack-react-native-paper:example)

My application is not closing according to these example, and the code is very similar, so much that I started based on these screens.

**Comment by raajnadar** [comment] 2019-01-19 07:59
Hey @eduardobarbiero,

What about sharing your routing code. I think you are not nesting the navigators properly.

**Comment by satya164** [comment] 2019-01-21 11:35
You're using react-navigation for the drawer, so you should refer to React Navigation's docs. What you render inside drawer (`DrawerItems` from paper in this case) doesn't affect it. I'm closing this since this is not related to paper.

**Closed by satya164** 2019-01-21 11:35 UTC

**Comment by eduardobarbiero** [comment] 2019-01-21 11:52
Sorry @satya164, but the Drawer is by paper.

My DrawerItems:
```
import * as React from 'react';
import { View, StyleSheet, Platform } from 'react-native';
import {
  Drawer,
  withTheme,  
  Divider,
  type Theme,
} from 'react-native-paper';
import { withNavigation } from 'react-navigation';

type Props = {
  theme: Theme,
  toggleTheme: Function,
  toggleRTL: Function,
  isRTL: boolean,
  isDarkTheme: boolean,
  navigation: any
};

type State = {
  open: boolean,
  drawerItemIndex: number,
};

class DrawerItems extends React.Component<Props, State> {
  state = {
    open: false,
    drawerItemIndex: 0,
  };

  _setDrawerItem = index => this.setState({ drawerItemIndex: index });

  render() {    
    const { colors } = this.props.theme;

    return (
      <View style={[styles.drawerContent, { backgroundColor: colors.surface }]}>

        <Drawer.Item
          label={"Guarnição"}
          key={0}
          icon="directions-car"
          onPress={
            () => {
              this._setDrawerItem(0);
              this.props.navigation.navigate("home");
            }
          }
        />
        <Drawer.Section title="Detentos">
          <Drawer.Item
            label={"Mapa"}
            key={1}
            icon="map"
            onPress={
              () => {
                this._setDrawerItem(1);
                this.props.navigation.navigate("prisionersMap");
              }
            }
          />
          <Drawer.Item
            label={"Visitas"}
            key={2}
            icon="room"
            onPress={
              () => {
                this._setDrawerItem(2);
                this.props.navigation.navigate("prisioner");
              }
            }
          />
        </Drawer.Section>

        <Drawer.Section title="Preferencias">
          <Drawer.Item
            label={"Configurações"}
            key={3}
            icon="settings"
            onPress={
              () => {
                this._setDrawerItem(3);
                this.props.navigation.navigate("configuration");
              }
            }
          />
          <Divider />
          <Drawer.Item
            label={"Sair"}
            key={3}
            icon="exit-to-app"            
            onPress={
              () => {
                this._setDrawerItem(3);
                this.props.navigation.navigate("login");
              }
            }
          />
        </Drawer.Section>
      </View>
    );
  }
}

```
See in: https://github.com/callstack/react-native-paper/blob/c0f7f90e67a45a075d296f04a2412a600e309969/src/index.js#L19

**Comment by raajnadar** [comment] 2019-01-21 11:55
Actually the feature that you are asking is by default. And paper only provides UI elements. If you can generate a working snack I can help you mostly the issue is with drawer setup.

**Comment by satya164** [comment] 2019-01-21 13:02
@eduardobarbiero paper doesn't provide a drawer component. `Drawer.Items` is the list of items you render inside the drawer component. The `Drawer` component comes from `createDrawerNavigator` from `react-navigation`
