### ISSUE TITLE
HelperText is't working properly

### ISSUE THREAD

**Issue by Alain00** [callstack/react-native-paper#1457] opened 2019-11-06 21:54 UTC
## Enviroment
I use vscode,  with TypeScript 3.4.5
## Description
Seems that props type definition for HelperText component are't working properly, i don't have autocompletion for his props. Also when visible is set to false, there is some space occupied by the component
## Reproducible Demo
```jsx
<HelperText //does not autocomplete this props
    type='error' 
    visible={false}>
    Error
</HelperText> 
```

**Comment by Barbiero** [comment] 2019-11-07 13:06
> Also when visible is set to false, there is some space occupied by the component

I feel like this is a feature and not a bug. When you use the `visible` prop, you can easily chain `TextInput`s and `HelperText`s:

    <TextInput label="email" value={email} onChangeText={setEmail} error={isEmailError}/>
    <HelperText type="error" visible={isEmailError}>Invalid email</HelperText>
    <TextInput label="password" value={password} onChangeText={setPassword} secureTextEntry error={isPasswordError}/>
    <HelperText type="error" visible={isPasswordError}>Password too short</HelperText>

By doing it like that, the components are neatly spaced. If you *really* want to hide that sapce, you should instead use a conditional expression:

    { isError ? <HelperText type="error">Error!</HelperText> : null }

**Comment by Alain00** [comment] 2019-11-07 13:15
@Barbiero  if see like that, it could be. Thanks

But there still the problem of the types
> Seems that props type definition for HelperText component are't working properly, i don't have autocompletion for his props

**Comment by Trancever** [comment] 2019-11-07 15:09
@Alain00 Is autocompletion working for other components properly?

**Comment by Alain00** [comment] 2019-11-07 15:52
> @Alain00 Is autocompletion working for other components properly?

Yes

**Comment by Barbiero** [comment] 2019-11-07 16:47
For that matter, I've tested here with Typescript 3.7.2 and it's showing incomplete information, ie. `type` and  `visible` seem to be omitted.

![image](https://user-images.githubusercontent.com/5532443/68408912-f7902d80-0164-11ea-8388-d48c81549581.png)

**Comment by Trancever** [comment] 2019-12-12 15:09
Duplicate of #1412

**Closed by Trancever** 2019-12-12 15:09 UTC
Labels: HelperText, Typescript, bug
