### ISSUE TITLE
Use react-native-gesture-handler for buttons

### ISSUE THREAD

**Issue by ferrannp** [callstack/react-native-paper#703] opened 2018-12-17 14:27 UTC
In order to fix #500, it might be an option.

**Comment by RichardLindhout** [comment] 2019-02-07 15:52
Can be closed now since the issue is resolved?

**Comment by ferrannp** [comment] 2019-02-07 21:23
@RichardLindhout we are still considering switching touchables to gesture handler for 3.0 that is why we kept this open.

**Comment by Trancever** [comment] 2019-03-18 07:44
Closing, because touchables from gesture-handler are not accessible

**Closed by Trancever** 2019-03-18 07:44 UTC
Labels: 3.0

**Comment by DeniferSantiago** [comment] 2021-01-11 15:59
@Trancever according to the documentation there is a way that the buttons are accessible [doc](https://docs.swmansion.com/react-native-gesture-handler/docs/component-buttons)
