### ISSUE TITLE
How to add a shadow for BottomNavigation?

### ISSUE THREAD

**Issue by egor-a-trubnikov-panov** [callstack/react-native-paper#715] opened 2018-12-27 15:05 UTC
I need to add a shadow for BottomNavigation on top. But I can't do that. I added style to barStyle. But it has no effect.
```js
import React from 'react';

import {MainScreen} from "../screens/MainScreen";
import {IncomesScreen} from "../screens/IncomesScreen";;
import {createAppContainer} from "react-navigation";
import {createMaterialBottomTabNavigator} from "react-navigation-material-bottom-tabs";
import {theme} from "../../constants/Theme";


export default createAppContainer(createMaterialBottomTabNavigator(
    {
        Main: {screen: MainScreen},
        Incomes: {screen: IncomesScreen}
    },
    {
        initialRouteName: 'Main',
        activeTintColor: theme.colors.accent,
        inactiveTintColor: theme.colors.backdrop,
        barStyle: {
            backgroundColor: theme.colors.background,
            shadowOffset: {width: 0, height: 2,},
            shadowColor: '#000000',
            shadowOpacity: 1,
            shadowRadius: 7,
        },
        labeled: true,
        shifting: false,
    }
));
```

**Comment by jaysbytes** [comment] 2019-04-16 11:37
Shadow API works only for iOS, if you want to set a shadow on android you should use `elevation` prop. However, due to how elevation works you will not be able to get the same result as with usgin shadow on iOS. Your code works for me in `react-native-paper` example app on iOS so I'm closing issue for now.

**Closed by jaysbytes** 2019-04-16 11:37 UTC

**Comment by SupaMario123** [comment] 2020-04-27 10:57
@jayu  can you upload a code snipped of your working version? I have the same Problem.

**Comment by jayu** [comment] 2020-04-27 11:31
@SupaMario123 It was one year ago, I don't remember the snippet I tested :p I probably edited navigation setup in paper example app.

**Comment by thallada** [comment] 2020-11-06 19:19
Adding an `elevation` style to `barStyle` in `createMaterialBottomTabNavigator` does not work for me. No shadow is displayed above the bottom tab bar on Android. The shadow styles in @jayu's example work to display a shadow on iOS though.

Any idea how to solve that? Maybe `BottomNavigation` is getting rendered in some parent that has `overflow: hidden` set?

**Comment by JPStrydom** [comment] 2023-02-15 11:46
The `elevation` style does not work on Android. No matter what we set the `elevation` style in the `barStyle` (or the `style`) to the shadow still won't show up on Android. This can easily be reproduced in [this Snack](https://snack.expo.dev/?platform=android). Here's what it looks like on Android: 
![image](https://user-images.githubusercontent.com/25905330/219019050-a10a4d10-de68-499f-9166-fb34e914586d.png)
