### ISSUE TITLE
FAB, Card component has WARN in iOS app

### ISSUE THREAD

**Issue by georgezhang** [callstack/react-native-paper#3838] opened 2023-04-23 04:08 UTC
### Current behaviour
When put FAB or Card component in iOS app, there are WARN like:
(ADVICE) View #17 of type RCTView has a shadow set but cannot calculate shadow efficiently. Consider setting a background color to fix this, or apply the shadow to a more specific component.

### Expected behaviour
No warning should show or had option to specify the background color.

"react-native": "0.71.6"
"react-native-paper": "^5.3.1"

**Comment by DimitarNestorov** [comment] 2023-04-23 07:26
Please update to the newest Paper version. Duplicate of #3593.

**Closed by DimitarNestorov** 2023-04-23 07:26 UTC
Labels: bug
