### ISSUE TITLE
Radio button inner circle is off-center 

### ISSUE THREAD

**Issue by hichemfantar** [callstack/react-native-paper#3628] opened 2023-01-28 11:45 UTC
### Current behaviour
As you can see, the selected radio button circle is skewed to the right and not centered.

### Expected behaviour
The radio button inner circle should be properly centered.

### Preview
![Screenshot_20230128-123916.jpg](https://user-images.githubusercontent.com/34947993/215264595-54325458-b9ee-4bcc-93c9-0f9552ff3123.jpg)

The inner circle should be centered like this:
![Screenshot_20230128-124357.jpg](https://user-images.githubusercontent.com/34947993/215264688-09489bf1-16ad-47d9-a714-be80b8f631f5.jpg)

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | x.x.x
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | x.x.x

**Comment by MitAbhay** [comment] 2023-01-29 09:43
I want to work on this bug, can I?

**Comment by hichemfantar** [comment] 2023-01-29 10:55
@MitAbhay Sure thing. A pull request is most welcome 🚀

**Comment by lukewalczak** [comment] 2023-01-30 08:50
Hey @hichemfantar, could you please fill the environment data from the issue template? I've just checked `RadioButton` component on the Paper app from the store, on the Pixel 4a, and it looks correctly.

**Comment by hichemfantar** [comment] 2023-01-30 10:08
> Hey @hichemfantar, could you please fill the environment data from the issue template? I've just checked `RadioButton` component on the Paper app from the store, on the Pixel 4a, and it looks correctly.

I'm also using the paper app from the playstore.
I opened the app on a OnePlus N100.

**Comment by lukewalczak** [comment] 2023-01-30 20:01
Hey @hichemfantar, unfortunately, I don't have an access to the OnePlus N100 and looks like that issue can be specific to the device. 

> I want to work on this bug, can I?

@MitAbhay sure, if you are able to observe the issue don't hesitate to propose a fix 🙌🏽

**Comment by hichemfantar** [comment] 2023-01-31 10:53
@lukewalczak I'm getting the same effect in the expo go app which is written in react native. Very bizarre.
![Screenshot_20230131-114942__01.jpg](https://user-images.githubusercontent.com/34947993/215740864-2da1551e-949d-4558-b707-991d610b0614.jpg)

**Comment by MitAbhay** [comment] 2023-01-31 10:54
> Hey @hichemfantar, unfortunately, I don't have an access to the OnePlus N100 and looks like that issue can be specific to the device.
> 
> > I want to work on this bug, can I?
> 
> @MitAbhay sure, if you are able to observe the issue don't hesitate to propose a fix 🙌🏽

@lukewalczak  Sure, I am looking for the same.

**Comment by lukewalczak** [comment] 2023-03-31 11:43
Since the root cause most likely exists outside of the Paper library, I'm closing the issue. However, if you come across any new findings or thoughts, please feel free to share them here with everyone.

**Closed by lukewalczak** 2023-03-31 11:43 UTC
Labels: bug, RadioButton

**Comment by ruff-exec** [comment] 2026-01-22 12:13
@lukewalczak I think this is still an important issue on the react native paper side and should be further investigated as I have a device with a small screen size where this issue still comes up and the expo go app on the same device does not have this issue as told by @clicktodev. Maybe expo fixed the issue react native paper still has

**Comment by ram-a-dhan** [comment] 2026-04-18 13:37
i made a PR that fixes this. check it out.
