### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by ThailanHigor** [callstack/react-native-paper#956] opened 2019-03-29 02:15 UTC
How to change the library icons to MaterialCommunityIcons?
I need another icon.

I'm using in BottomNavigation in routes state.
```
state = {
    index: 0,
    routes: [
      { key: 'home', title: 'home', icon: 'cards'},
    ],
};
```

**Comment by satya164** [comment] 2019-03-29 14:01
Duplicate of #926

**Closed by satya164** 2019-03-29 14:01 UTC
Labels: question
