### ISSUE TITLE
A simple TextInput and a multiline TextInput have diferent label height.

### ISSUE THREAD

**Issue by LuigiMaestrelli** [callstack/react-native-paper#1989] opened 2020-06-15 14:44 UTC
### Current behaviour

A simple TextInput and a multiline TextInput have diferent label height.

### Expected behaviour

It should be the same, or it should be a way to customize the label

### Screenshots

![image](https://user-images.githubusercontent.com/5038871/84670721-d9f62400-aefc-11ea-839f-c86eeb5808bf.png)

### What have you tried

Searched for some way to customize the label props

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Both
| react-native          | 0.62.2
| react-native-paper    | 3.10.1
| node                  | 14.4.0
| npm or yarn           | yarn
| expo sdk              | Not using expo

**Comment by raajnadar** [comment] 2020-06-15 14:47
Duplicate of https://github.com/callstack/react-native-paper/issues/1570

**Closed by raajnadar** 2020-06-15 14:47 UTC
