### ISSUE TITLE
Material Bottom Tabs Navigator active screen tabBarColor does not work

### ISSUE THREAD

**Issue by syedmohsin7975** [callstack/react-native-paper#3743] opened 2023-03-10 19:03 UTC

**Comment by tjaniczek** [comment] 2023-03-21 10:08
Hi @syedmohsin7975 , could you please share more details about this issue? Small snack with this problem replicated would be perfect. I just tested this with new version and everything seems to be working:
<img width="449" alt="image" src="https://user-images.githubusercontent.com/7429558/226574430-dd588ba9-7309-479d-b7d9-90f090b9afd7.png">

Please note that coloured tabs are only available in MD2, when `shifting` style is used: https://callstack.github.io/react-native-paper/docs/components/BottomNavigation/#props 
I hope that helps!

**Comment by lukewalczak** [comment] 2023-03-31 11:29
Closing the issue due to missing input from the author despite our effort to help.

**Closed by lukewalczak** 2023-03-31 11:29 UTC
Labels: needs repro, BottomNavigation, question

**Comment by AjmirSarker** [comment] 2023-10-14 07:53
@lukewalczak  , Here is my code . The problem is  tabBarColor is not changing when I change the screens. I'm  using  @react-navigation/material-bottom-tabs as navigator.


<Tab.Screen
          name="Home"
          activeBackgroundColor="red"
          component={Home}
          options={{
            tabBarIcon: () => <Icon color="red" name="rocket" size={20} />,
            tabBarLabel: 'Hoe',
            tabBarColor: 'lightblue',
          }}
        />
        
        this is the code i used
