### ISSUE TITLE
Improve layout of multiline TextInputs

### ISSUE THREAD

**Issue by kpsroka** [callstack/react-native-paper#234] opened 2018-02-07 11:27 UTC
MD specs: https://material.io/guidelines/components/text-fields.html#text-fields-field-types

Current state of affairs: for `<TextInput multiline label="Multiline" />` we render
![screenshot_20180207-120443](https://user-images.githubusercontent.com/24893014/35913961-d6359dc8-0c01-11e8-85dd-c4a17d922639.png)

**Comment by Trancever** [comment] 2018-02-23 15:26
Hey, I tried to find what cause such behaviour and what I found is that plain TextInput from react-native doesn't render properly. It looks like it's not adding enough bottom margin when multiline prop is set to true.
![textinput](https://user-images.githubusercontent.com/18584155/36601678-025693ce-18b6-11e8-9d6e-ab3213e017db.png)

**Comment by Trancever** [comment] 2018-02-26 13:49
I investigated it deeper and results are interesting. Multiline TextInput renders correctly in apps created with react-native-cli but renders as on images above when used in apps created with crna or expo xde. It looks like it's a bug in expo.

**Comment by raajnadar** [comment] 2019-01-24 07:39
I tried reproducing it in snack but it seems like the issue is fixed in paper v2.

https://snack.expo.io/@raajnadar/react-native-paper-multiline-texinput

So I think it is safe to close this issue.

**Closed by raajnadar** 2019-01-24 07:39 UTC
