### ISSUE TITLE
EventEmitter.removeListener('change', ...): Method has been deprecated. Warning

### ISSUE THREAD

**Issue by pushpender-singh-ap** [callstack/react-native-paper#2984] opened 2021-11-20 14:34 UTC
### Warning
EventEmitter.removeListener('change', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`

### Code sample
import { Menu } from 'react-native-paper';
        <Menu
                            visible={menu}
                            onDismiss={() => setmenu(false)}
                            anchor={<Ionicons
                                onPress={() => setmenu(true)}
                                name={"settings-sharp"}
                                size={24}
                                color={"#222"}
                            />}>
                            <Menu.Item onPress={() => { }} title="Download" />
                            <Menu.Item onPress={() => { }} title="Report" />
                            <Menu.Item onPress={() => { }} title="Cancel" />
                        </Menu>

### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/73298854/142730101-712c30f4-5652-49d9-a432-5ee50d0d756c.png)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |  android
| react-native          |  0.66.2
| react-native-paper    |   ^4.10.1
| node                  |     v14.18.1
| npm or yarn           |    npm
| expo sdk              |   no

GITHUB REPO:- https://github.com/pushpender-singh-ap/sampleRepo

**Comment by lukewalczak** [comment] 2021-11-22 11:01
Hey @pushpender-singh-ap, what version of `@types/react-native` are you using?

**Comment by pushpender-singh-ap** [comment] 2021-11-22 11:17
> Hey @pushpender-singh-ap, what version of `@types/react-native` are you using?
i am not using this dep

**Comment by lukewalczak** [comment] 2021-11-22 11:33
Are you able to create simple repo reproducing your issue?

**Comment by pushpender-singh-ap** [comment] 2021-11-22 11:35
> Are you able to create simple repo reproducing your issue?

yes, sure I will make and inform you later.

**Comment by pushpender-singh-ap** [comment] 2021-11-23 03:13
@lukewalczak sample repo clone and press Paper Button and press hardware back you automatically get the warning.

Repo Link:- https://github.com/pushpender-singh-ap/sampleRepo

**Comment by lukewalczak** [comment] 2021-11-23 13:58
Hey @pushpender-singh-ap, I quickly looked at your example and ran it, however I was not able to observe the warning. Since you are facing it only on Android platform, I assume something can be wrong with your environment/setup, especially that [PR](https://github.com/callstack/react-native-paper/pull/2918) fixing that behavior was merged couple weeks ago.

**Comment by pushpender-singh-ap** [comment] 2021-11-23 14:00
@lukewalczak Hey, i will provide you the video asap.

**Comment by AndrewIsBest69** [comment] 2021-11-25 06:13
The same happens for me using Modal, tried npm update and npm install but that didn't fix it.

**Comment by jwisbeck** [comment] 2021-11-25 13:47
Hi here! I too am facing the same issue and am seeing some deprecated functions in the lib

**Comment by mrojas18** [comment] 2021-12-03 22:41
the same here, using Menu Component... 

"react-native": "0.66.0",
"react-native-paper": "^4.10.1",

**Comment by lukewalczak** [comment] 2021-12-05 19:40
I've just run `npm view react-native-paper dist.tarball` which generated link to package's tarball and code looks properly in the mentioned components such as `Menu` or Provider`.

**Comment by pushpender-singh-ap** [comment] 2021-12-06 13:46
@lukewalczak See this

<a href="url"><img src="https://user-images.githubusercontent.com/73298854/144856696-8f9afdbc-fdc8-4d1c-b57c-adf48320d3ca.gif" height="400" width="600" ></a>

<a href="url"><img src="https://user-images.githubusercontent.com/73298854/144856846-8d1aec8e-7dd3-461b-9e22-7e3b29cb46ed.gif" height="400" width="600" ></a>

**Comment by jwisbeck** [comment] 2021-12-09 08:58
> I've just run `npm view react-native-paper dist.tarball` which generated link to package's tarball and code looks properly in the mentioned components such as `Menu` or `Provider`.

can you share an example? I think that the code may be using deprecated functions.

**Comment by lukewalczak** [comment] 2021-12-09 09:52
> can you share an example? I think that the code may be using deprecated functions.

What kind of example do you want me to share? By running the above command you receive the URL to the registry's tarball and after downloading it you can look at given package code from npm.

**Comment by pushpender-singh-ap** [comment] 2021-12-09 16:52
@lukewalczak you see the above gif?

**Comment by lukewalczak** [comment] 2021-12-09 17:16
@pushpender-singh-ap Yes, I can see, however since I'm not able to reproduce your issue, maybe you can propose the fix and send a PR?

**Comment by pushpender-singh-ap** [comment] 2021-12-09 17:22
> @pushpender-singh-ap Yes, I can see, however since I'm not able to reproduce your issue, maybe you can propose the fix and send a PR?

ok, I will try, and if you have any solution share it with us.

**Comment by root-io** [comment] 2021-12-11 18:03
I had the exact same warning, any chance this line trigger the deprecated code?

https://github.com/callstack/react-native-paper/blob/main/src/components/Menu/Menu.tsx#L264

**Comment by pushpender-singh-ap** [comment] 2021-12-12 16:15
@lukewalczak check the PR this issue solved

**Comment by lukewalczak** [comment] 2021-12-12 21:14
Thanks @root-io and @pushpender-singh-ap  for your input, I was finally able to observe the bug related to `Menu` component. Also, I've left the comment in the PR.

@AndrewIsBest69, @jwisbeck could you please attach your minimal repro which demonstrates the issue if it's not related to the `Menu` component?

**Comment by pushpender-singh-ap** [comment] 2021-12-13 04:39
@lukewalczak Check PR comment and see the Video attached in PR

**Comment by pushpender-singh-ap** [comment] 2021-12-14 13:43
@lukewalczak  check one time this commit is also working on  0.64+ & below 0.64 I tested on 0.63 & as well as 0.66.

Maybe this help you if you think that way it is better than the previous one inform me I will again generate PR.

https://github.com/pushpender-singh-ap/react-native-paper/commit/943d743272451840d25506372678c817f5e2ec81#diff-79e0d805785bbe8a0f585efebc274478388e7ce83323d87a7492930efd924de3

**Comment by lukewalczak** [comment] 2021-12-21 10:33
@AndrewIsBest69 @jwisbeck @root-io please try to install the library from that [PR](https://github.com/callstack/react-native-paper/pull/3017) and please let me know if it fixes your issue ✌🏽

**Comment by root-io** [comment] 2021-12-22 21:05
> @AndrewIsBest69 @jwisbeck @root-io please try to install the library from that [PR](https://github.com/callstack/react-native-paper/pull/3017) and please let me know if it fixes your issue ✌🏽

No more warning using your PR with react-native 0.66.4 👍
I have another issue, the menu takes time to open but it was already the case before your fix so seems good to me thanks

**Comment by pushpender-singh-ap** [comment] 2021-12-30 17:15
@lukewalczak PR?

**Closed** 2022-01-17 11:03 UTC
Labels: wip, needs follow up

**Comment by kbhh** [comment] 2022-02-11 08:05
Facing the same issue...

 using 
 "react-native": "0.65.1",
 "react-native-paper": "^4.11.2",
 
 seems to work when i make some tweeks below though on the Menu component. 
 
<img width="660" alt="Screen Shot 2022-02-11 at 11 04 16 AM" src="https://user-images.githubusercontent.com/13124694/153556576-3bbb34ea-8bc2-4502-92e1-b1c0076e8d25.png">

**Comment by lukewalczak** [comment] 2022-02-11 08:13
Problem should be solved in version `4.12.0-alpha.0`
