### ISSUE TITLE
TextInput outlined mode: label has unknown shadow

### ISSUE THREAD

**Issue by mehulmpt** [callstack/react-native-paper#657] opened 2018-11-15 13:36 UTC
### Current behaviour
Please see attached:

![screenshot 2018-11-15 at 7 01 25 pm](https://user-images.githubusercontent.com/10388889/48556136-13257700-e909-11e8-9c63-6ea064be8d79.png)

### Expected behaviour

There should not be any weird shadow.

### Code sample

Here's what I'm using to render this input field:

```jsx
<TextInput
	label='Name'
	testID="input"
	mode="outlined"
	theme={{ colors: { placeholder: 'grey', background: '#f5f6f5', text: 'grey', primary: '#5d5d5d' }}}
	style={styles.input}
	value={ this.state.name === undefined ? name : this.state.name }
	onChangeText={name => this.setState({ name })}
/>
```

and here's the parent config:

```js
const theme = {
	...DefaultTheme,
	colors: {
		...DefaultTheme.colors,
		text: '#565656',
		disabled: '#ffffff',
		primary: '#3f51b5'
	},
	fonts: {
		regular: "AirbnbCereal"+fontSuffix+"-Book",
		medium: "AirbnbCereal"+fontSuffix+"-Medium",
		bold: "AirbnbCereal"+fontSuffix+"-Bold"
	}
}
```

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.57.3
| react-native-paper    | 2.2.4
| node                  |  8.9
| npm or yarn           | yarn

**Comment by raajnadar** [comment] 2018-11-16 16:00
Hey, create a reproduce able [snack here](https://snack.expo.io), It will be easier to debug the issue

**Comment by mehulmpt** [comment] 2018-11-30 11:12
No its still same @ferrannp

**Comment by imerkle** [comment] 2018-12-03 20:35
Same

**Comment by ayaanmd21** [comment] 2018-12-11 13:22
same here

**Comment by ayaanmd21** [comment] 2018-12-11 13:23
please fix it

**Comment by raajnadar** [comment] 2018-12-11 13:30
No one can help you without an issue reproducing snack or github repo.

**Comment by imerkle** [comment] 2018-12-11 13:52
Its fixed now atleast for me

**Comment by ayaanmd21** [comment] 2018-12-13 13:06
how

**Comment by ayaanmd21** [comment] 2018-12-13 13:06
> No one can help you without an issue reproducing snack or github repo. Comments like "same", "me too", "+1" won't help to find the issue.

in snack its working fine

**Comment by raajnadar** [comment] 2018-12-13 13:36
Generate this issue in a test repository.

**Comment by ayaanmd21** [comment] 2018-12-14 09:56
there are two label which label text color is transparent that is creating shawdow

**Comment by TheRealNate** [comment] 2018-12-14 18:08
Here's a Snack showing the issue @Wilson-Lim (and myself) are experiencing.

https://snack.expo.io/@natekidzideaz/Y291cm

If you look closely at the label when TextInput is focused or has text inside it, you'll see the grey rectangle behind the label text.

**Comment by TheRealNate** [comment] 2018-12-14 18:14
@Wilson-Lim Seems that the reason this is happening is related to configuration.

See https://github.com/callstack/react-native-paper/blob/master/src/components/TextInput.js#L49
```
In `outlined` mode, the background color of the label is derived from `colors.background` in theme or the `backgroundColor` style.
```

This means that if you haven't configured backgroundColor correctly, it will assume light grey.

This however is unrelated to the issue @mehulmpt is having.

**Comment by fgagneten** [comment] 2019-01-05 16:50
I have the same problem. Solution for that?

**Comment by toddpi314** [comment] 2019-01-14 00:41
Same. 

Android fix is to adjust this value to `27`: https://github.com/callstack/react-native-paper/blob/master/src/components/TextInput.js#L20 

I'm guessing this is theme related.

**Comment by TheRealNate** [comment] 2019-01-16 19:13
@toddpi314 It seems like a lot of people are having this issue. Should this become a customizable value in the theming?

**Comment by DAKZH** [comment] 2019-01-18 21:50
This is happening because there are TWO labels on top of each other. One of them has color of background.

But it doesn't work on android because even if your background is white and color text is white, you will still see the text.

<img width="179" alt="2019-01-19 3 48 36" src="https://user-images.githubusercontent.com/4746394/51414566-22d96a00-1b9d-11e9-8c7b-55f2d4ec2b35.png">


The second label is used to "cut" the border. I recommend to calculate the width of background from label, not just insert it with background color.

**Comment by DAKZH** [comment] 2019-01-18 22:10
Remove this block:

{mode === 'outlined' && label ? (
          // When mode == 'outlined', the input label stays on top of the outline
          // The background of the label covers the outline so it looks cut off
          // To achieve the effect, we position the actual label with a background on top of it
          // We set the color of the text to transparent so only the background is visible
          <AnimatedText
            pointerEvents="none"
            style={[
              styles.outlinedLabelBackground,
              {
                backgroundColor,
                fontFamily,
                fontSize: MINIMIZED_LABEL_FONT_SIZE,
                // Hide the background when scale will be 0
                // There's a bug in RN which makes scale: 0 act weird
                opacity: this.state.labeled.interpolate({
                  inputRange: [0, 0.9, 1],
                  outputRange: [1, 1, 0],
                }),
                transform: [
                  {
                    // Animate the scale when label is moved up
                    scaleX: this.state.labeled.interpolate({
                      inputRange: [0, 1],
                      outputRange: [1, 0],
                    }),
                  },
                ],
              },
            ]}
            numberOfLines={1}
          >
            {label}
          </AnimatedText>
        ) : null}



And set background to the label

**Comment by jbinda** [comment] 2019-07-16 10:52
In 3.0 branch (current master) it should not be a problem anymore.

**Closed by jbinda** 2019-07-16 10:52 UTC
Labels: needs repro
