### ISSUE TITLE
Typescript error in version 4.10.0 

### ISSUE THREAD

**Issue by cuongdo926** [callstack/react-native-paper#2965] opened 2021-11-06 06:14 UTC
I use this react-native-paper@^4.10.0 with typescript but got some typing errors

![image](https://user-images.githubusercontent.com/85761020/140596319-b28cc3b5-9d1a-4982-88c5-e4cb9bf4ccdf.png)

package.json
```
{
  "name": "expo-app-",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "start": "react-native start"
  },
  "dependencies": {
    "expo": "~43.0.0",
    "expo-splash-screen": "~0.13.3",
    "expo-status-bar": "~1.1.0",
    "expo-updates": "~0.10.5",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.2",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-paper": "^4.10.0",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.8.0",
    "react-native-web": "0.17.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~17.0.1",
    "@types/react-native": "~0.64.2",
    "typescript": "^4.4.4"
  },
  "private": true
}
```

**Comment by dennis-gonzales** [comment] 2021-11-06 14:13
Same error showed on me when my version was upgraded.
Going back to lower version like `"react-native-paper": "^4.9.2"` worked for me

**Comment by cuongdo926** [comment] 2021-11-06 16:04
It doesn't work for me. It seems the errors are different for each version of @types/react-native and many components have typing issues

**Comment by maccuaa** [comment] 2021-11-08 19:18
Seeing the same issue. I think it's related to #2929

```json
"react-native": "0.66.2",
"react-native-paper": "4.10.0",

"@types/react-native": "0.66.3",
```

Getting these types of error anywhere i'm using certain React Native Paper components:

```
Property 'tvParallaxProperties' is missing in type '{ size: number; color: string; type: string; name: string; }' but required in type 'Pick<Partial<IconProps> & Partial<ThemeProps<Partial<IconProps>>>, "type" | "reverse" | "name" | "color" | ... 65 more ... | "brand">'.

119       <ListItem.Chevron

Type '{ children: Element; topDivider: true; }' is missing the following properties from type 'Pick<TouchableHighlightProps & { containerStyle?: StyleProp<ViewStyle>; disabledStyle?: StyleProp<ViewStyle>; ... 6 more ...; children?: any; } & Partial<...>, "testID" | ... 45 more ... | "bottomDivider">': hasTVPreferredFocus, tvParallaxProperties

210     <ListItem topDivider>

**Comment by rvdende** [comment] 2021-11-09 07:28
Incase someone else runs into this issue, this is how you force a version on a package:

`npm install react-native-paper@4.9.2`

Then restart VSCode so it reloads the type files.

**Comment by rvdende** [comment] 2021-11-09 07:37
It's a bit tricky to reproduce in an online playground it seems as so far I've not found one that shows the same error as you get in a local VSCode instance. However this should be very common to any new projects.

**Comment by kendallroth** [comment] 2021-11-10 12:12
Can confirm that rolling back to `4.9.2` resolves the issues I was having with this (for me it was **any** of the `react-native-paper` components based on the `Text` component). Obviously not ideal, but at least it works.

**Comment by enagorny** [comment] 2021-11-10 17:32
I think it might be broken by this commit https://github.com/callstack/react-native-paper/commit/a3563ad979e81688693c8712b12aa1e952a4442b

**Comment by aaronfg** [comment] 2021-11-16 06:05
Thanks for this. Just did an upgrade to RN 66.3 and started upgrading all of my dependencies and ran into this super annoying bug.

Rolling back to `4.9.2` and  the `@types/react-native` to `0.65.5` fixed it for me.

**Comment by simonbuerger** [comment] 2021-11-16 10:38
@lukewalczak just a heads up here that the 4.10.0 version doesn't seem to have an updated lib folder as the compiled types still contain the outdated properties from @types/react-native 0.65.5. Perhaps just a missed yarn install before deploying that version?

**Comment by lukewalczak** [comment] 2021-11-16 16:43
Could you please try version 4.10.1 and let me know what is the result?

**Comment by iM-GeeKy** [comment] 2021-11-16 20:25
> Could you please try version 4.10.1 and let me know what is the result?

I'm still seeing the errors as previously mentioned above after upgrading to 4.10.1.

**Comment by lukewalczak** [comment] 2021-11-16 20:38
@iM-GeeKy Could you please create example repo presenting the issue?

**Comment by RichardLindhout** [comment] 2021-11-16 20:44
For me there are also errors everywhere

**Comment by iM-GeeKy** [comment] 2021-11-17 00:43
> @iM-GeeKy Could you please create example repo presenting the issue?

Here is a basic [repo](https://github.com/iM-GeeKy/react-native-paper-test) showing some (maybe not all) of the errors. `yarn start` should get you going. The project was created using [Expo Quick Start](https://docs.expo.dev/#quick-start).

**Comment by simonbuerger** [comment] 2021-11-17 07:26
@lukewalczak on the latest react native and react-native-paper my errors are gone, personally

**Comment by adamgajzlerowicz** [comment] 2021-11-17 09:58
I confirm:
react-native-paper 4.10.1
react-native 0.66.3
@types/react-native 0.66.4

The errors are gone, along with old warning messages.

Thank you!

**Comment by lukewalczak** [comment] 2021-11-17 14:50
I think using paper `v4.10.1` with types `0.66.x` solves the problem.

**Comment by kendallroth** [comment] 2021-11-24 21:35
I can confirm that this is still an issue with `react-native-paper@4.10.1` and `@types/react-native@0.64.19`

**Comment by SpeedOfSpin** [comment] 2021-12-05 11:48
Still an issue for me as well. Rolled back to 4.9.2 with react native 0.66.3 and errors are gone

**Comment by arnaudbzn** [comment] 2021-12-13 18:35
It works for me with: `react-native-paper@4.11.1` and `@types/react-native@0.66.1`.
But I'm using Expo SDK 42 that relies on React Native 0.63 :pensive:
And Expo SDK 44 Beta is using React Native 0.64.3...

**Comment by fedorin-git** [comment] 2021-12-17 13:49
Hello everyone. Get the same issue using ProgressBar

`<ProgressBar indeterminate={inProgress} color={PURPLE_400} />`

returns error
`TS2741: Property 'children' is missing in type '{ indeterminate: true; color: string; }' but required in type 'Pick '.`

Investigated that type Props in `/src/components/ProgressBar.tsx` does not contain 'children' as optional so I have to pass it calling component

`<ProgressBar indeterminate={inProgress} color={PURPLE_400} children />`

**Comment by lukewalczak** [comment] 2021-12-17 19:17
@fedorin-git could you please share your tech stack _(version of rn, rn paper and types)_ on which I can reproduce it?

**Comment by fedorin-git** [comment] 2021-12-20 09:27
> @fedorin-git could you please share your tech stack _(version of rn, rn paper and types)_ on which I can reproduce it?

"react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
"react-native-paper": "^4.11.1",
"@types/react": "~16.9.35",
"@types/react-native": "~0.63.2"

**Comment by yashash99** [comment] 2021-12-24 02:44
This a working component which takes text props
`title.d.ts`
```
declare type Props = React.ComponentProps<typeof Text> & {
    children: React.ReactNode;
};
```

`title.ts`
```
type Props = React.ComponentProps<typeof Text> & {
  children: React.ReactNode;
};
```

I noticed this issue in Text and Dialog.Title component. This components have type file generation as mentioned in https://github.com/callstack/react-native-paper/issues/2965#issuecomment-971308124
Also as shown in https://github.com/callstack/react-native-paper/issues/2965#issue-1046436075 the issue is only seen in editor, no issue in expo web development logs.

I am using latest expo and rn-paper version.

```
"dependencies": {
    "expo": "~44.0.0",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-art": "^17.0.2",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-paper": "^4.11.1",
    "react-native-web": "0.17.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.64.12",
    "typescript": "~4.3.5"
  },
```

**Comment by elashpear** [comment] 2022-01-06 20:15
I am running into similar issues. I am on RN 0.63.4. I tried rolling back to react-native-paper 4.9.2 which looks like it was the last version compiled against RN 0.63. But I still see an error for example when I try to use the paper text component:

```
js/PaperTest.tsx:31:12 - error TS2741: Property 'dataDetectorType' is missing in type '{ children: string; }' but required in type 'Pick<TextProps & { style?: StyleProp<TextStyle>; theme: Theme; } & RefAttributes<{}>, "key" | "ref" | "style" | "onLayout" | ... 32 more ... | "dataDetectorType">'.

31           <Text>{`${modalText}`}</Text>
              ~~~~
```

It appears as this property is only used on Android, and even then should not be a required property, so I don't know why this raised an error.

Versions:
```
  "@types/react": "16.14.0",
  "@types/react-native": "0.63.4",
  "react-native": "0.63.4",
  "react-native-paper": "4.9.2",
```

**Comment by NoerNova** [comment] 2022-03-10 18:49
Upgrade @types/react-native to latest version fixed issue.

**Comment by francesco-clementi-92** [comment] 2022-04-14 17:27
I tried every combination with @types/react-native but nothing works. Which one did you find to work correctly? 
I'm using react-native 0.67.4, react-native-paper 4.12.0 and @types/react-native 0.67.4, but I have a lot of typescript error in vscode

**Comment by fabriziocucci** [comment] 2022-05-08 16:23
Experiencing a similar issue with `4.12.0` and `Card`, `ActivityIndicator` and `IconButton` components:
```
'Card' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<(Pick<OutlinedCardProps & Pick<ViewProps & RefAttributes<View> & { children: ReactNode; style?: false | ... 4 more ... | WithAnimatedArray<...>; theme: Theme; }, keyof ViewProps | keyof RefAttributes<...>> & { ...; } & { ...; }, keyof ViewProps | ... 3 more ... | keyof OutlinedCard...' is not a valid JSX element.ts(2786)
```

My `package.json`:
```
"dependencies": {
    ...
    "expo": "~44.0.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-paper": "^4.12.0",
  },
  "devDependencies": {
    ...
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.64.12",
    "typescript": "~4.3.5"
  },
```

Suggestions?

**Comment by raajnadar** [comment] 2022-05-08 16:34
Add this in `package.json`

```
"resolutions": {
	"@types/react": "<version-of-react>"
},
```

**Comment by kendallroth** [comment] 2022-06-03 19:05
> Add this in `package.json`
> 
> ```
> "resolutions": {
> 	"@types/react": "<version-of-react>"
> },
> ```

I could certainly be wrong, but isn't this a Yarn-specific feature? It _appears_ to have a [counterpart](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) in NPM as of `v8`, but may be misunderstanding this as well?

**Comment by JohnGeorgiadis** [comment] 2022-08-03 08:31
I had the same issue on `4.12.4`.  I solve it with @kendallroth's suggestion, but I do not understand why we need to use resolutions for this, can't we have react native paper work with the latest `@types/react` ?

**Comment by raajnadar** [comment] 2022-08-03 10:00
The issue will go away without resolution or any hacks if you use RN 0.69 or Expo SDK 46 as it is based on React 18

**Comment by raajnadar** [comment] 2022-08-03 10:03
I will close this as this was just a warning and we already have quick solutions in this thread..!

**Closed by raajnadar** 2022-08-03 10:03 UTC
Labels: repro provided
