### ISSUE TITLE
TextInput unknown line near floating label

### ISSUE THREAD

**Issue by nikhilSriva** [callstack/react-native-paper#2532] opened 2021-01-29 20:26 UTC
### Current behaviour

![Screenshot_20210130-014910](https://user-images.githubusercontent.com/25061961/106323557-9be81d80-629d-11eb-94cc-9b7c897fda07.jpg)

### Expected behaviour

![Screenshot_20210130-015124](https://user-images.githubusercontent.com/25061961/106323714-dbaf0500-629d-11eb-8c66-659c8046bb26.jpg)

### Code sample

` <View>
                            <TextInput
                                onChangeText={() => {}}
                                label={'Pet Age'}
                                value={values.petAge}
                            />
                        </View>`
### What have you tried

Tried tweaking styles (paddingVertical) but no success.
Also, it's randomly occuring.
### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | Android 11
| react-native          | 0.63.4
| react-native-paper    | 4.5.0
| node                  | 14.15.1
| react-native-vector-icons | 7.1.0

Thanks!

**Comment by leonelhenriquez** [comment] 2021-03-30 23:56
Did you manage to solve?

I have the same problem

**Comment by lukewalczak** [comment] 2021-04-15 13:40
Looks like the same issue as https://github.com/callstack/react-native-paper/issues/2644. Prolly it can be related to Android version 11. Are you able to reproduce that issue on the real device?

**Comment by pradumn26** [comment] 2021-04-21 09:41
i am facing the same issue on android 10

**Comment by lukewalczak** [comment] 2021-04-22 12:20
That issue should be fixed in the latest version (4.8.0) 🤞🏽

**Closed** 2021-04-22 12:21 UTC
Labels: TextInput, needs investigation
