### ISSUE TITLE
How to display a right icon inside a TextInput?

### ISSUE THREAD

**Issue by seyaobey** [callstack/react-native-paper#2154] opened 2020-08-24 14:08 UTC
I'm struggling to display a right icon inside a text-input. From this [article announcing version 4.0](https://callstack.com/blog/react-native-paper-4-0/#Second_Sub_Point_1), it looks like it is possible. But there is no clear instruction in docs on how to achieve it. On the documentation page, for `TextInput`, there are `left` and `right` props which I suppose should display e.g an icon. This is my view (Expo + React-Native):

```
<TextInput label="__label__" right={() => <FontAwesome5 name="edit" size={24} color="red" />}  />
```
I also tried this way:
```
<TextInput label="__label__" right={<FontAwesome5 name="edit" size={24} color="red" />}  />
```

In both cases nothing is displayed. What is the use of properties `left` and `right` and how to display an icon inside a TextInput? 
Thank you for support.

react-native (expo version): https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz
react-native-paper: ^4.0.1
@expo/vector-icons: ^10.0.0

**Comment by rizshivalli** [comment] 2020-08-24 18:52
I am also having the same issue

**Comment by seyaobey** [comment] 2020-08-24 20:46
@rizshivalli thanks form your answer. I finally figured it out myself and was about to report my findings here. 
The documentation should probably be updated. It took me hours to figure it out. People with less patience may just turn away and abandon this excellent library...
(not bashing at all, just making an honest suggestion...)

**Comment by rizshivalli** [comment] 2020-08-25 04:45
Please close the issue if the issue is resolved

**Comment by karthikveeraj** [comment] 2020-08-25 15:08
@rizshivalli, Can you please post this example in the <TextInput> sample so that people won't have to search google to figure this out.

**Closed** 2020-08-25 16:15 UTC

**Comment by pixelass** [comment] 2021-02-01 15:40
this should really be covered somewhere in the docs which IMHO are not useful in many cases.

@rizshivalli do you want to document things like this? are you open to PRs that add better docs for components?

**Comment by bhavesh-trentium** [comment] 2023-12-20 04:52
> I was also having the same issue
> 
> i fixed it using `<TextInput.Icon name="Icon-Name" />` You can pass the name of an icon from MaterialCommunityIcons. This will use the react-native-vector-icons library to display the icon.
> 
> ```
> import * as React from 'react';
> import { View } from 'react-native'
> import { TextInput } from 'react-native-paper';
> 
> const InputComponent = () => {
>  const element = <TextInput.Icon name="lock-outline" />
>   return (
>     <TextInput
>       label="Email"
>       mode='outlined'
>       style={{ backgroundColor: 'transparent' }}
>       right= {element}
>       left={element}
>     />
>   );
> };
> 
> export default InputComponent;
> ```

Input.Icon is a not gived proper Icon as like FatherIcons
