### ISSUE TITLE
Bug: Broken styles in Docs section

### ISSUE THREAD

**Issue by iamciro** [callstack/react-native-paper#3608] opened 2023-01-19 16:20 UTC
### Current behavior:

Currently, when entering to the Docs page, all the styles seem to be broken, as seen in the preview. 

### Expected behaviour:

The Docs section should be rendered in the right way, with the styles correctly shown. 

### How to reproduce?

Enter to [React Native Paper's Docs section](https://callstack.github.io/react-native-paper/index.html)

### Preview

![Screenshot from 2023-01-19 13-17-27](https://user-images.githubusercontent.com/20261044/213495490-64e1519b-7579-4ba4-9543-ced57d43daf3.png)

**Comment by lukewalczak** [comment] 2023-01-19 17:36
Duplicate of: https://github.com/callstack/react-native-paper/issues/3607

**Closed by lukewalczak** 2023-01-19 17:36 UTC
