### ISSUE TITLE
TextField label has margin initialValues

### ISSUE THREAD

**Issue by douglaszaltron** [callstack/react-native-paper#1354] opened 2019-09-27 19:20 UTC
## Environment

react-nativo > 0.61.1
react-native-paper `3.0.0-alpha.5`

## Description

In input text fields, when fields are filled in by redux or the label has a different margin than the text. after you change the value back to normal

## Reproducible Demo

![image](https://user-images.githubusercontent.com/4502670/65796245-7a73a080-e142-11e9-83f1-ca94a0f0520d.png)

**Comment by mishojan** [comment] 2019-10-03 20:40
PLEASE FIX THIS :((((((

**Comment by satya164** [comment] 2019-10-03 20:43
@mishojan please send a pull request

**Comment by RichardLindhout** [comment] 2019-10-22 21:02
Will try to fix this, this week probably Tuesday.

**Comment by RichardLindhout** [comment] 2019-10-31 20:49
Ok little bit later than Tuesday but I  found the cause :-)

**Comment by RichardLindhout** [comment] 2019-10-31 20:57
The code here is never ran when you have an initial value
```
https://github.com/callstack/react-native-paper/blob/master/src/components/TextInput/TextInput.tsx#L210
```
There is an initial value available in the state so it's never changed there
https://github.com/callstack/react-native-paper/blob/master/src/components/TextInput/TextInput.tsx#L191

**Comment by RichardLindhout** [comment] 2019-10-31 21:03
Pull request: https://github.com/callstack/react-native-paper/pull/1440

**Comment by RichardLindhout** [comment] 2019-10-31 23:46
FIx for this merged: https://github.com/callstack/react-native-paper/pull/1441

**Closed** 2019-10-31 23:47 UTC
