### ISSUE TITLE
Outline line overlaps label

### ISSUE THREAD

**Issue by GrandLineAR** [callstack/react-native-paper#3759] opened 2023-03-16 10:28 UTC
Outline line overlaps label

https://user-images.githubusercontent.com/43339997/225590146-615965a0-96f6-41da-b9fb-922dc893ea4c.MP4

<img width="332" alt="Screenshot at Mar 16 14-29-07" src="https://user-images.githubusercontent.com/43339997/225589512-98d72fd0-486b-4acc-8763-9d75b8335d71.png">

"react-native-paper": "^5.4.1"

**Comment by lukewalczak** [comment] 2023-03-16 18:27
Hey @GrandLineAR, please provide the snack or attach the code snippet which allow us to reproduce the issue.

**Comment by jeremyfalldev** [comment] 2023-03-31 19:36
@lukewalczak We see this issue when we use 'backgroundColor: transparent'.

```
<TextInput
  mode="outlined"
  label="Name"
  style={{ backgroundColor: 'transparent' }}
/>
```

**Comment by lukewalczak** [comment] 2023-04-01 10:00
> @lukewalczak We see this issue when we use 'backgroundColor: transparent'.

Thanks, will take a look into it.

**Comment by GrandLineAR** [comment] 2023-04-08 17:01
> @lukewalczak We see this issue when we use 'backgroundColor: transparent'.
> 
> ```
> <TextInput
>   mode="outlined"
>   label="Name"
>   style={{ backgroundColor: 'transparent' }}
> />
> ```

Yes, thank you! That's my omission, the documentation mentions that

**Comment by lukewalczak** [comment] 2023-06-21 16:59
I believe we have encountered a limitation of the outlined text input – it will **not** work well with the **patchy** background such as an image or gradient. 

The issue arises when the input is focused, the label is lifted up to the outline, causing a break in the border. To achieve the desired design, there is rendered label background view, with the same background color as the input, used to cover the border at the point of the break:

```
<TextInput style={{backgroundColor: 'yellow'}}
```
<img width="340" alt="image" src="https://github.com/callstack/react-native-paper/assets/22746080/575b779c-31e1-4784-a736-e606eedde9e4">

----
Passing `backgroundColor: 'transparent'` into `TextInput` ends with a missing cover break in the border:

<img width="342" alt="image" src="https://github.com/callstack/react-native-paper/assets/22746080/aca24dd0-3a4e-4905-b4f5-ad262a3f4281">

---

To achieve the desired "transparent effect" in the outlined text input, I believe the best approach is to set the input's background color to match the background color of the screen, however this method works seamlessly when the colors are uniform.

I'm going to create a `Known issue` section in the documentation where that limitation will be mentioned in `TextInput` component.

**Comment by Martijncvv** [comment] 2023-06-22 19:24
I also noticed a slight overlap of the label.
![image](https://github.com/callstack/react-native-paper/assets/70589073/51959962-ff45-45ab-8338-f764e27b3aad)
`   const outlineStyle: ViewStyle = {
        borderRadius: styles.radius.large,
    };

    return (
        <TextInput
            mode="outlined"
            label={label}
            value={text}
            outlineStyle={outlineStyle}
            onChangeText={text => setText(text)}
            theme={{ colors: { primary: styles.Colors.grey.default, outline: styles.Colors.grey.default } }}
        />
    );`

**Comment by RichardLindhout** [comment] 2023-06-23 11:21
This can be fixed on the web though with fieldset

**Comment by RichardLindhout** [comment] 2023-06-23 11:22
See an old PR for that: https://github.com/callstack/react-native-paper/pull/883
Material UI uses the fieldset hack too :)

**Comment by Martijncvv** [comment] 2023-06-23 15:18
> 

Thanks a lot. Do you have an idea how to see the code? The "Files changed" tab of the PR leads to a dead link.

**Comment by RichardLindhout** [comment] 2023-06-29 22:37
Yeah @Martijncvv it only works on web so I don't think it's usable since it won't work on iOS/React Native

**Comment by lelimit** [comment] 2023-07-12 10:55
It's still a problem in react-native-paper 5.9.1. 
I got this problem when upgrading react native from 0.71.8 to 0.72.1

**Closed** 2023-08-02 07:49 UTC
Labels: bug, TextInput

**Comment by robertcabrera4871** [comment] 2023-09-13 20:57
I am still seeing this issue after the PR

**Comment by redbluenat** [comment] 2023-10-29 23:44
The issue still exists in:
    "react-native-paper": "5.11.1",

**Comment by ravithoria** [comment] 2024-02-17 10:54
Still facing issue in: react-native-paper: 5.12.3

**Comment by JoshCarse** [comment] 2024-06-03 07:23
Yeah still getting issue in: "react-native-paper": "5.12.3".
Only when using custom label component as @redbluenat mentioned.
Using string for `label` works fine but I need to use custom label component.

**Comment by joannakasinska** [comment] 2024-08-19 20:39
I worked around it by adding backgroundColor: 'color' to the styles:
`<RNPaperTextInput label='label' style={{backgroundColor: 'white' }}/>`

**Comment by t-fraczek** [comment] 2024-10-25 10:16
"react-native-paper": "5.12.3".
![Zrzut ekranu 2024-10-25 o 12 15 52](https://github.com/user-attachments/assets/49b95c38-7996-4538-88b9-ae59393eb167)
