### ISSUE TITLE
descriptionNumberofLines  not working 

### ISSUE THREAD

**Issue by ezekel** [callstack/react-native-paper#2251] opened 2020-09-21 13:47 UTC
I'm setting descriptionNumberofLines  so that the description can have
3 lines but it only shows elipsis

RN version : react-native@0.63.2

RNP version: react-native-paper@4.2.0

react-native-vector-icons:react-native-vector-icons@7.1.0

```
 renderItem={({item}) => (
                            <TouchableOpacity onPress={()=>navigation.navigate('ClosedDetails',{id:item.id})}>
                                <List.Item
                                    title={item.id}
                                    descriptionNumberofLines={3}
                                    description={<><Caption>{item.amount}{"\n"}{item.created_by}{"\n"}{item.created_at}</Caption></>}
                                    left={props => <Icon {...props} color={Colors.blue500} size={30} style={{marginVertical:6}} name="cc-paypal"  />}
                                />
                            </TouchableOpacity>

                        )}

```

![image](https://user-images.githubusercontent.com/6830057/93772480-742edc00-fc51-11ea-8364-15a3308e7021.png)

**Comment by RichardLindhout** [comment] 2020-11-20 21:41
Duplicate of: https://github.com/callstack/react-native-paper/issues/2251
```
I thinks it's because of the Caption element the description should just be a string not an element
```

**Closed** 2021-01-05 19:34 UTC
