### ISSUE TITLE
Textinput's outline appears behind the label if Text component is passed to label

### ISSUE THREAD

**Issue by martenjurgens** [callstack/react-native-paper#4114] opened 2023-10-06 00:39 UTC
### Current behaviour
If Text component is passed to the label of a TextInput, the outline isn't hidden properly and appears behind the label.

### Expected behaviour
Acts the same as if a string is passed to the label.

### How to reproduce?

```javascript
const [text, setText] = React.useState("");

<TextInput
   // label={"Last name"}
  label={<Text style={{ color: "black" }}>Last name</Text>}
  value={text}
  onChangeText={text => setText(text)}
   />
``` 

### Preview

How it looks like when Text component is passed to label
![image](https://github.com/callstack/react-native-paper/assets/55079581/30f1f55f-b0a6-4835-9f8e-dd587ec0ea73)

How it looks like when string is passed to label
![image](https://github.com/callstack/react-native-paper/assets/55079581/6ea807f5-4178-4cff-913b-1edc7b0cfcbc)

### Your Environment

| software                      | version
| --------------------- | -------
| android                        | 13
| react-native                | 0.72.5
| react-native-paper    | 5.10.6

**Comment by Lev-Shapiro** [comment] 2023-10-06 07:38
I'll start working on this today soon, please assign this issue to me

**Comment by lukewalczak** [comment] 2023-10-06 07:43
Thanks @Lev-Shapiro!

**Closed** 2023-10-12 12:25 UTC
Labels: bug

**Comment by WanYingT** [comment] 2023-11-03 14:20
How do I remove the label background just like this?
<img width="313" alt="Screenshot 2023-11-03 at 10 19 12 PM" src="https://github.com/callstack/react-native-paper/assets/45457137/95501d23-030b-4085-99dc-a3fe5a6a0f7e">

**Comment by Lev-Shapiro** [comment] 2023-11-03 14:24
I just checked my code that was merged and it doesn't seem to have any problems with background labeling. Could you share why you decided to comment on this issue? Anyway, I'll be happy to fix this

**Comment by WanYingT** [comment] 2023-11-04 00:32
I found that passing RNP Text component  to the label props will still have this problem occurred, while using RN Text component is totally fine. Also, the problem I mentioned happens when I  add { borderRadius: 30 } to the TextInput component to make it close to design, label background seems to be overflow. I understand I can remove the white background by using colors: { background: 'transparent' }, but it will not leave a field for that. Is there any possible approach to fix?

**Comment by Lev-Shapiro** [comment] 2023-11-04 06:45
Yes, creating a new issue and giving code to reproduce the problem
