### ISSUE TITLE
Tap on the Banner component:  the focus-lost event is not fired

### ISSUE THREAD

**Issue by borgogelli** [callstack/react-native-paper#838] opened 2019-02-12 17:30 UTC
If the focus is on a SearchBar component (or any other) and I tap on a Banner component, nothing happens.
While every time I tap on a View component, the SearchBar losts the focus.
I think that the second behavior is preferible,

**Comment by Trancever** [comment] 2019-02-12 20:29
Hi, thanks for spotting the issue. I'll take a look tomorrow.

**Comment by Trancever** [comment] 2019-02-13 15:30
@borgogelli Could you provide Snack that reproduces issue? You can modify [this one](https://snack.expo.io/@trensik/amused-cookie)

**Comment by borgogelli** [comment] 2019-02-14 09:48
@Trancever thank you for your reply. After some test I can say that it's not an issue of react-native-paper. But please see my example https://snack.expo.io/ryb2wnGB4
If first I tap on the Searchbar and then on the red zone (the ScrollView) I lost the focus. I think that this the right behavior for every users. But if I don't use the ScrollView, and I tap on other UI elements, nothing happens and the focus remains on the Searchbar. I think that the last behavior is not very user-friendly. What do you think about ?

**Comment by satya164** [comment] 2019-02-14 10:55
Agree that it's not user-friendly, but the behavior comes from react-native. We can't really do anything about it.

Closing since this issue is non-actionable for us.

**Closed by satya164** 2019-02-14 10:55 UTC
