### ISSUE TITLE
Tab title not hide when lost focus and Icon color not change when focus

### ISSUE THREAD

**Issue by huytran123** [callstack/react-native-paper#554] opened 2018-09-20 05:02 UTC
Tab title not hide when lost focus and Icon color not change when focus, it is happen when first time run app

In-correct:
![screenshot_2018-09-20-11-30-25-131_com carwash](https://user-images.githubusercontent.com/24526707/45796892-fe43b300-bccc-11e8-8e71-d9cc76b467b2.png)

Correct:
![screenshot_2018-09-20-11-37-29-799_com carwash](https://user-images.githubusercontent.com/24526707/45796907-0d2a6580-bccd-11e8-9633-7d220c76dd44.png)

I have deleted this code: 
 if (prevProps.navigationState.index === this.props.navigationState.index) { return;  }

In function "componentDidUpdate" in file "BottomNavigation.js" to fix this error. 

Please check it. 

"react": "16.5.0",
 "react-native": "0.57.0",
 "react-native-paper": "^2.0.1",
android: 7.1

**Comment by ferrannp** [comment] 2018-09-20 10:58
Can you provide a Snack of this? Are you also using Debugger when running it?

**Comment by huytran123** [comment] 2018-09-20 15:33
i do not thinking so. i am running an DEV mode , not DEBUG mode. 
I am using this example: https://callstack.github.io/react-native-paper/bottom-navigation.html
please see video: https://youtu.be/ZKdCBqQeiK0
I am running on android 8.1(Mi A1)

**Comment by satya164** [comment] 2018-09-20 15:48
Can you share your code?

**Comment by huytran123** [comment] 2018-09-20 15:52
this my code @satya164 :

import React from 'react';
import { BottomNavigation, Text } from 'react-native-paper';

const MusicRoute = () => <Text>Music</Text>;

const AlbumsRoute = () => <Text>Albums</Text>;

const RecentsRoute = () => <Text>Recents</Text>;

class MyComponent extends React.Component {
  state = {
    index: 0,
    routes: [
      { key: 'music', title: 'Music', icon: 'queue-music' },
      { key: 'albums', title: 'Albums', icon: 'album' },
      { key: 'recents', title: 'Recents', icon: 'history' },
      { key: 'music', title: 'Music', icon: 'queue-music' },
    ],
  };

  _handleIndexChange = index => this.setState({ index });

  _renderScene = BottomNavigation.SceneMap({
    music: MusicRoute,
    albums: AlbumsRoute,
    recents: RecentsRoute,
  });

  render() {
    return (
      <BottomNavigation
        navigationState={this.state}
        onIndexChange={this._handleIndexChange}
        renderScene={this._renderScene}
      />
    );
  }
}

export default class App extends React.Component {

    render() {

        return (<MyComponent />
        );
    }
}

**Comment by victorkvarghese** [comment] 2018-09-25 10:33
@satya164 Will upload the code tonight. 

PS: I'm using [createMaterialBottomTabNavigator](https://reactnavigation.org/docs/en/material-bottom-tab-navigator.html). But the documentation specifically says the component uses  BottomNavigation component from react-native-paper. 

I will upload the example code and a proper gif tonight

**Comment by huytran123** [comment] 2018-09-25 10:55
@satya164 : you can see this video:  https://youtu.be/ZKdCBqQeiK0, 
this video match with code which i post for you
@victorkvarghese : i have found this error. You can read my post to fix this error if you need to fix them

**Comment by victorkvarghese** [comment] 2018-09-25 10:55
@satya164 @ferrannp 

```
import React from 'react';
import { createMaterialBottomTabNavigator } from 'react-navigation-material-bottom-tabs';
import { createStackNavigator } from 'react-navigation';
import Home from 'app/screens/Home';
import Business from 'app/screens/Business';
import News from 'app/screens/News';
import Offers from 'app/screens/Offers';
import TabIcon from 'app/components/TabIcon';

import BusinessSubScreen from 'app/screens/BusinessSubScreen';
import BusinessDetail from 'app/screens/BusinessDetail';

const HomeTabIcon = ({ tintColor }) => (
    <TabIcon name="home" tintColor={tintColor} />
);
const BusinessTabIcon = ({ tintColor }) => (
    <TabIcon name="business" tintColor={tintColor} />
);
const NewsTabIcon = ({ tintColor }) => (
    <TabIcon name="public" tintColor={tintColor} />
);
const OffersTabIcon = ({ tintColor }) => (
    <TabIcon name="loyalty" tintColor={tintColor} />
);

const BusinessStack = createStackNavigator({
    Business: {
        screen: Business,
        navigationOptions: { header: null }
    },
    BusinessSubScreen: {
        screen: BusinessSubScreen,
        navigationOptions: { header: null }
    }
});

const BottomNavigation = createMaterialBottomTabNavigator(
    {
        Home: {
            screen: Home,
            navigationOptions: { tabBarIcon: HomeTabIcon }
        },
        Business: {
            screen: BusinessStack,
            navigationOptions: { tabBarIcon: BusinessTabIcon }
        },
        News: {
            screen: News,
            navigationOptions: { tabBarIcon: NewsTabIcon }
        },
        Offers: {
            screen: Offers,
            navigationOptions: { tabBarIcon: OffersTabIcon }
        }
    },
    {
        initialRouteName: 'Home',
        activeColor: '#C2202D',
        inactiveColor: '#95a5a6',
        barStyle: { backgroundColor: '#FFFFFF' }
    }
);

const MyApp = createStackNavigator(
    {
        BottomNavigation: {
            screen: BottomNavigation,
            navigationOptions: { header: null }
        },
        BusinessDetail: {
            screen: BusinessDetail,
            navigationOptions: { header: null }
        }
    },
    { initialRouteName: 'BottomNavigation' }
);

export default MyApp;
```
**When app launches**
![screenshot_20180925-162349__01](https://user-images.githubusercontent.com/15869386/46010215-7e0fba00-c0df-11e8-97bd-89c294921562.jpg)

**When we select another tab for first time**

![screenshot_20180925-160532__02](https://user-images.githubusercontent.com/15869386/46010223-81a34100-c0df-11e8-8b2c-eb2ec3f65060.jpg)

**Comment by ferrannp** [comment] 2018-10-04 10:33
@huytran123 we cannot reproduce it, what device are you using?

**Comment by victorkvarghese** [comment] 2018-10-04 10:37
@ferrannp Using createBottomTabNavigator instead of createMaterialBottomTabNavigator fixes the issue. 

but the expo app for react native paper ..Bottom Navigation works fine. 

Might be related to this [lib](https://github.com/react-navigation/react-navigation-material-bottom-tabs)

**Comment by gawrysiak** [comment] 2018-10-04 10:41
For me it happens quite a lot when using hot reloading and doing code changes. Standard reload fixes it instantly. Can't really reproduce it properly, but I'll try when I see it next time.

**Comment by satya164** [comment] 2018-10-04 10:45
also do you have chrome debugger connected when this happens?

**Comment by huytran123** [comment] 2018-10-05 04:59
@ferrannp i am using Mi A1 (Android 8.1)

**Comment by HenryQuan** [comment] 2018-10-08 03:08
I am also having this issue on OnePlus 5 (Android 8.1). I have tested on iPhone simulators but it seems that it is Android only. Only tested on debug mode.

IOS (left) Android (right)
![nav](https://user-images.githubusercontent.com/6754708/46590935-dc3a9500-cb02-11e8-9185-7f666fc31c83.gif)

This is my code.
```
<BottomNavigation navigationState={this.state} activeColor={blue500}
    barStyle={{backgroundColor: 'white'}} inactiveColor={grey700} 
    onIndexChange={this._handleIndexChange} renderScene={this._renderScene} />
```

**Comment by ferrannp** [comment] 2018-11-09 13:39
Can you try `2.2.4`? Should be fixed.

**Comment by satya164** [comment] 2018-11-09 13:55
#637

**Closed** 2018-11-09 13:55 UTC
Labels: needs more info
