### ISSUE TITLE
Paper 4.x ProgressBar w/ progress={0} throws string must be rendered in <Text> error

### ISSUE THREAD

**Issue by pjsandwich** [callstack/react-native-paper#4142] opened 2023-10-20 16:57 UTC
### Current behaviour

I have a component that uses `<ProgressBar/>`, if a value of 0 is passed the component throws the following error:
```
Error: Text strings must be rendered within a <Text> component.
```

Wondering if anyone else has seen this?

### Expected behaviour

Value of 0 should not throw an error

### What have you tried so far?

I created a workaround by setting values of 0 to 0.01 if they are initially 0

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 15
| android                        | x
| react-native                | 0.71.7
| react-native-paper    | 4.12.1
| node                            | 20.3.1
| npm or yarn                | yarn 3.6.0
| expo sdk                     | 48.0.0

**Comment by pjsandwich** [comment] 2023-10-20 16:59
Feel free to close, I have a workaround, but value of 0 should not cause an error, particularly an error that doesn't really yield any insight to the cause of the error.

**Comment by lukewalczak** [comment] 2023-10-21 12:50
Hey @pjsandwich, could you please check whether the issue occurred on the latest version (v5.11.0)? Alternatively, could you please attach the repro, so we can check it on our end?

**Comment by lukewalczak** [comment] 2023-11-23 13:55
Closing due to missing bug reproduction.

**Closed by lukewalczak** 2023-11-23 13:55 UTC
Labels: bug, ProgressBar
