### ISSUE TITLE
In 5.0.0 release candidates: <Text /> without variant means no fontFamily is applied

### ISSUE THREAD

**Issue by getadapt** [callstack/react-native-paper#3358] opened 2022-09-06 10:18 UTC
**Is your feature request related to a problem? Please describe.**
In 5.0.0 candidates, if you don't specify <Text /> `variant=`, no `fontFamily` is applied.

**Describe the solution you'd like**
Perhaps there should be a fallback for variant? Maybe to `"bodyMedium"`?

**Describe alternatives you've considered**
Or perhaps throw an error to make it clear that this property is required, though this would make upgrading more annoying.

In any case, without error message or default variant, it is strange for the basic `Text` component to get into any situation where it falls back to default font.

**Additional context**
Context is that I tried out a release candidate and was surprised my fonts disappeared without error feedback.

**Comment by lukewalczak** [comment] 2022-09-06 10:22
Hej @getadapt, thanks for the feedback. I will investigate the problem.

**Comment by lukewalczak** [comment] 2022-09-07 21:59
Hey @getadapt, I've checked your issue, however, I was not able to reproduce it. On the following [snack](https://snack.expo.dev/bdRU9LJfD), I was able to observe custom font on the `Text` component without specified `variant`.  If I misunderstood your problem, please correct me or preferably attach your snack, presenting the bug.

**Comment by bsubedi26** [comment] 2022-10-03 22:52
@lukewalczak Facing a similar issue. I think @getadapt is getting at that no font family is applied when you don't specify a variant and without inlining the font family as style prop.

In v2 it was defaulting to `theme.fonts.regular` but in v3 there is no font family being set:
https://github.com/callstack/react-native-paper/blob/main/src/components/Typography/Text.tsx#L131

Is it possible to set a default value font family from the theme for v3, here? We have a use case where it would be great if the `<Text>` had a default font family without specifying a `variant` prop.

**Comment by lukewalczak** [comment] 2022-10-17 08:50
Fixed via #3409

**Closed by lukewalczak** 2022-10-17 08:50 UTC
Labels: Typography, repro provided, Material You (v5)
