### ISSUE TITLE
Warning after importing react-native-paper : Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

### ISSUE THREAD

**Issue by Steffi3rd** [callstack/react-native-paper#930] opened 2019-03-16 11:20 UTC
<img width="548" alt="Capture d’écran 2019-03-16 à 12 16 32" src="https://user-images.githubusercontent.com/814410/54474491-c9c93380-47e5-11e9-8d78-b802a130a4fd.png">

**Comment by max10rogerio** [comment] 2019-03-18 23:03
Same problem...

**Comment by satya164** [comment] 2019-03-18 23:49
Duplicate of #639

**Closed by satya164** 2019-03-18 23:49 UTC

**Comment by gitmudassir** [comment] 2019-10-18 23:00
You are probably importing something from file "AppbarHeader.js"  into "Appbar.js", then importing something again from "Appbar.js" into "AppbarHeader.js" .
Cross check all the imports from both the files and see if there's any such cycle.

**Comment by M4urici0GM** [comment] 2020-02-10 17:41
I`m still getting the warnings, what could it be?

**Comment by gitmudassir** [comment] 2020-02-11 01:07
> I`m still getting the warnings, what could it be?

Check this out : 
https://stackoverflow.com/questions/55664673/require-cycles-are-allowed-but-can-result-in-uninitialized-values-consider-ref/58459108#58459108

**Comment by harveyconnor** [comment] 2020-02-27 01:14
Still getting this issue.

**Comment by felipeinfantino** [comment] 2020-04-23 10:54
@harveyconnor 

Import each Item separate , for example you need a List Section with an accordion and a list item so go like : 

import  ListSection from 'react-native-paper/lib/commonjs/components/List/ListSection';
import  ListAccordion from 'react-native-paper/lib/commonjs/components/List/ListAccordion';
import  ListItem from 'react-native-paper/lib/commonjs/components/List/ListItem';

And then instead of <List.Section> (like in the docs) you use <ListSection> . That should be enough

**Comment by Ulfsaar-dev** [comment] 2020-05-27 16:39
Place the 'react-native-paper' at the very top of the Code.

**Comment by raajnadar** [comment] 2020-05-27 16:48
A PR to fix this issue is open here https://github.com/callstack/react-native-paper/pull/1851. Please be patient it will be merged soon.

**Comment by Alvarotony17** [comment] 2020-06-01 04:59
it solved this issue by doing this.
Place the import 'react-native-paper' at the very top of the Code. in the Index.js

**Comment by jyotiprakash111** [comment] 2020-06-22 09:58
i am still facing the  issue.  RN - version 62.2   "react-native-paper": "^3.10.1", please help. i am able to see blank screen on my emulator.

**Comment by fxbayuanggara** [comment] 2020-06-24 11:57
Place `import { Provider as PaperProvider } from 'react-native-paper';` directly after `import React from 'react';`, otherwise you'll get those warnings.

**Comment by vivian-verys** [comment] 2020-07-01 05:31
> Place `import { Provider as PaperProvider } from 'react-native-paper';` directly after `import React from 'react';`, otherwise you'll get those warnings.

This worked, totally forgot to wrap the entire app in this

**Comment by hungvu193** [comment] 2020-09-18 07:01
any update on this issue?

**Comment by waterydan** [comment] 2020-10-17 09:59
Still happening here as well. I'm hiding those warnings but it's not ideal.

**Comment by anonewb** [comment] 2020-10-21 15:10
`LogBox.ignoreLogs(["Require cycle:"]);`

**Comment by samuelseaton** [comment] 2020-10-29 19:03
still getting this issue

**Comment by kpose** [comment] 2020-11-23 15:12
why is this closed? still getting same error on "react-native-paper": "^4.4.1" and "react-native": "0.63.3". Any workaround yet?

**Comment by BatDroid** [comment] 2020-11-23 16:36
> @harveyconnor
> 
> Import each Item separate , for example you need a List Section with an accordion and a list item so go like :
> 
> import ListSection from 'react-native-paper/lib/commonjs/components/List/ListSection';
> import ListAccordion from 'react-native-paper/lib/commonjs/components/List/ListAccordion';
> import ListItem from 'react-native-paper/lib/commonjs/components/List/ListItem';
> 
> And then instead of <List.Section> (like in the docs) you use < ListSection > . That should be enough

For people wondering ... This Fixed my problem...

**Comment by josiaharkson** [comment] 2020-12-07 20:25
@harveyconnor 

@BatDroid's suggestion worked well for me. In my `index.js` file I imported directly from the modules' directory.

instead of

```
import {Provider as PaperProvider} from 'react-native-paper';
```
try importing like:
```
import PageProvider from 'react-native-paper/lib/commonjs/core/Provider';
```

It works well for me!

**Comment by kamalkemo** [comment] 2020-12-14 15:27
still looking for a solution

**Comment by dunloop** [comment] 2021-01-18 14:50
add `module:react-native-paper/babel` to your babel.config.js.

My babel.config.js:
```js
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    ["module:react-native-dotenv"],
    ["module:babel-plugin-module-resolver", {
      "alias": {
        "src": "./src"
      }
    }],
    ["module:react-native-paper/babel"]
  ]
};
```
