### ISSUE TITLE
iOS 13++ and dark mode changing text color

### ISSUE THREAD

**Issue by Foskas** [callstack/react-native-paper#1381] opened 2019-10-10 11:20 UTC
## Description

I'm using an app bar with white background and black status bar text. When using iOS 13++ and Dark Mode, the status bar text color changes to white (only when app bar renders).
Is there any way to fix this ?

## Reproducible Demo

- Use an iphone with iOS version >= 13
- Set dark to false (app bar or header)
- Status bar text is white

**Comment by jaysbytes** [comment] 2019-10-11 18:24
Is it related to iOS version or rather bug in a paper in general? Does it happen in other components than `<AppBar/>` and `<Header/>`? 
Can you prepare a reproducible demo on [snack.io](snack.io) ?

**Comment by atrimn** [comment] 2019-10-14 03:46
temporary solution:
in your Appdelegate.m

`  if (@available(iOS 13.0, *)) {
    rootView.overrideUserInterfaceStyle = UIUserInterfaceStyleLight;
  }`

**Comment by satya164** [comment] 2019-10-14 09:27
Paper doesn't control statusbar color. Closing since it's not a bug in paper.

**Closed by satya164** 2019-10-14 09:27 UTC
Labels: needs repro

**Comment by Foskas** [comment] 2019-10-15 10:04
@satya164 I'll provide a code example to repo as soon as possible (require branch change and can't do it right now) but what you said is not 100% right because the bug does not happen when I remove the appbar component. It's only when I use the app bar component that the status bar text color changes from black to white.

**Comment by Foskas** [comment] 2019-10-15 14:29
`      <Surface style={styles.Surface}>
         {Platform.OS === 'android' ? (
          <StatusBar translucent={true} backgroundColor="transparent" barStyle="dark-content" />
        ) : null}
        <Appbar.Header style={styles.Header} statusBarHeight={styles.StatusBar.height}>
        {......}
        </Appbar.Header>
      </Surface>`

Here is the repo code. 
Thank you!
