### ISSUE TITLE
Topmost BottomNavigation scenes intercept clicks while not active

### ISSUE THREAD

**Issue by digitaltoad** [callstack/react-native-paper#2885] opened 2021-09-02 09:22 UTC
### Current behaviour

Using BottomNavigation with React Navigation on the web, the top most scene, (over simplifying, right most tab), if mounted, will intercept clicks while not active. This seems to be a problem with `pointer-events` within that scene.

### Expected behaviour

I would expect that when a tab is inactive, it does not intercept pointer events.

### Code sample

https://snack.expo.io/@digitaltoad/bottonnavigation-react-navigation-web-bug

### What have you tried

I've pulled back to `3.x` versions of `react-native-paper` and this problem disappears.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | N/A
| react-native          | 0.64.2
| react-native-paper    | 4.9.2
| react-native-vector-icons | 8.1.0
| node                  | 15.10.0
| yarn           | 1.22.10
| npm           | 7.5.3
| expo             | 42.0.0

https://snack.expo.io/@digitaltoad/bottonnavigation-react-navigation-web-bug

**Comment by digitaltoad** [comment] 2021-09-02 09:29
It still exists.

**Comment by Neyxo** [comment] 2021-10-04 15:07
I can reproduce it as well and I think this is the same issue as #2366

There seems to be a fix with #2548 but unfortunately, it doesn't seem like it's going to be merged..

**Comment by lukewalczak** [comment] 2021-12-15 15:36
Issue should be fixed by: https://github.com/callstack/react-native-paper/pull/2985. 
Please try to upgrade paper to the latest version `4.11.1`

**Closed by lukewalczak** 2021-12-15 15:36 UTC
Labels: repro provided
