### ISSUE TITLE
Drop shadow is hexagonal on circular IconButton 

### ISSUE THREAD

**Issue by lawrence-laz** [callstack/react-native-paper#3028] opened 2022-01-08 13:39 UTC
Not sure if this is issue with the library or my code, but I am experiencing an incorrectly shaped drop-shadow while using IconButton. That looks like this:
![image](https://user-images.githubusercontent.com/8823448/148646230-bf3c4483-3b1b-49bf-8874-418a815d5c94.png)
This is the code for it:
```js
<View style={{ position: 'absolute', top: 20, zIndex: 70, }}>
    <IconButton
        icon='arrow-left-circle'
        onPress={navigation.goBack}
        color={Colors.white}
        size={30}
        style={{
            shadowColor: 'rgba(1, 0, 0, 1)',
            shadowOpacity: 0.8,
            elevation: 6,
            shadowRadius: 25,
            shadowOffset: { width: 1, height: 13 }
        }}
    />
</View>
```

Any ideas?

[Reproduced in a Snack](https://snack.expo.dev/@lawrence_laz/paper-icon-button-shadow-issue)

**Comment by lukewalczak** [comment] 2022-01-12 22:23
Hey @lawrence-laz could you please provide more details about the platform and device on which you are facing that issue? I've just run your snack on physical device  and component along with the shadow is rendered correctly.

**Comment by lawrence-laz** [comment] 2022-01-14 13:21
I've experienced this locally on an emulated Android Pixel 3A device as well as remotely in the provided Snack when using a virtual Android device hosted by Expo (had to wait in a queue and unsure what concrete device was running there though).
Here's a screenshot from a Snack:
![image](https://user-images.githubusercontent.com/8823448/149521772-7b1139c0-f56d-4062-b9ec-86c9de7928cd.png)

**Comment by lukewalczak** [comment] 2022-01-14 13:25
Maybe it's some kind of rendering limitations on emulated device. Did you try it on the real device?

**Comment by lawrence-laz** [comment] 2022-01-14 13:31
Just ran the same Snack on a physical Android Samsung S8:
![Screenshot_20220114-152917_Expo Go](https://user-images.githubusercontent.com/8823448/149523185-d4b36eef-ccd2-4ae6-bc33-839aab45d386.jpg)

**Comment by lukewalczak** [comment] 2022-01-14 14:16
Yes, I've tested it on iPhone. I'm just wondering if that issue is specifically related to the library 🤔 Could you please try to apply your shadow to the different component, not related to the Paper, to ensure the problem exists in `IconButton`?

**Comment by lawrence-laz** [comment] 2022-01-14 14:29
I modified the [Snack](https://snack.expo.dev/@lawrence_laz/paper-icon-button-shadow-issue) to include `IconButton` with shadow (top left), simple React Native `View` with same shadow (top right), `IconButton` without a shadow (bottom left) and simple `View` without a shadow (bottom right):
![Screenshot_20220114-162541_Expo Go](https://user-images.githubusercontent.com/8823448/149531439-b11fd45b-a061-47f1-8483-0974d69e5070.jpg)

**Comment by matt-koevort** [comment] 2022-04-05 08:09
FYI also seeing this on a physical device (Samsung Galaxy S9) when using elevation on a simple View. Unrelated to this libray imo.

**Comment by lawrence-laz** [comment] 2022-04-15 08:03
> FYI also seeing this on a physical device (Samsung Galaxy S9) when using elevation on a simple View. Unrelated to this libray imo.

Are you seeing it using the same Snack as above?

**Comment by lukewalczak** [comment] 2023-03-31 12:07
Since the root cause most likely exists outside of the Paper library, I'm closing the issue. However, if you come across any new findings or thoughts, please feel free to share them here with everyone.

**Closed by lukewalczak** 2023-03-31 12:07 UTC
Labels: needs more info, Icon Button, repro provided
