### ISSUE TITLE
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

### ISSUE THREAD

**Issue by nurmohammed840** [callstack/react-native-paper#1867] opened 2020-04-28 05:45 UTC
![Image](https://raw.githubusercontent.com/nurmohammed840/ScreenShots/master/Screenshot%20(32).png)

I got this message after `import {createMaterialBottomTabNavigator} from '@react-navigation/material-bottom-tabs';`

And How can I rid of this warning?

**Comment by hugosbg** [comment] 2020-04-28 22:40
+1

**Comment by MinaroShikuchi** [comment] 2020-05-08 20:31
#638

**Comment by kamui545** [comment] 2020-07-14 06:15
@github-actions the issue is still there, please do not close.

Also, here's a related PR: https://github.com/callstack/react-native-paper/pull/1851

**Comment by unikvozm** [comment] 2020-12-08 15:36
The fixes are merged and will be available in the next release soon =)

**Closed by unikvozm** 2020-12-08 15:36 UTC
Labels: Keep opened
