### ISSUE TITLE
Label background is slightly mispositioned on web

### ISSUE THREAD

**Issue by eugeneford** [callstack/react-native-paper#4041] opened 2023-08-25 10:03 UTC
### Current behaviour
The background element for input label is slightly mispositioned on Web. 

### Preview
<img width="298" alt="image" src="https://github.com/callstack/react-native-paper/assets/16384615/45356cab-de2c-473d-92e1-28dd24726c1b">

### What have you tried so far?
I've managed to get a workaround by making a wrapper for TextInput component to add custom styles specifically for Web:

```jsx
<>
  <MaterialTextInput
    mode={mode}
    textColor={textColor}
    activeOutlineColor={activeOutlineColor}
    style={[
      {backgroundColor: "#fff"},
      style,
    ]}
    {...rest}
  />
  {Platform.OS === "web" && (
    createElement("style", {
      dangerouslySetInnerHTML: {
        __html: `
        [data-testid="text-input-outlined-label-background"] {
          margin-top: -2px;
        }`
      }
    })
  )}
</>
```

**Comment by RichardLindhout** [comment] 2023-08-26 15:33
It's only on latest react-native-web i downgraded for now to 0.18

**Comment by davidascii** [comment] 2023-08-28 04:26
Duplicate of #3825

**Comment by davidascii** [comment] 2023-08-28 04:48
Another possible workaround
```javascript
<TextInputPaper
    mode="outlined"
    ...
    outlineStyle={{...(Platform.OS === 'web' && {marginTop: '2px'})}}
/>
```

I've tried manually changing the 'top' value of the label by -2, and it also fixes(?) the problem
![](https://i.imgur.com/SBwf4hV.gif)

**Closed** 2023-09-18 19:17 UTC
Labels: bug
