### ISSUE TITLE
The example app on the README does not work due to the sdk version

### ISSUE THREAD

**Issue by agrcrobles** [callstack/react-native-paper#1496] opened 2019-12-02 15:39 UTC
## Environment

Android

## Description

The example app on the README does not work due to the sdk version

## Reproducible Demo

https://github.com/callstack/react-native-paper/blob/master/README.md#try-it-out

![EXPO APP](https://user-images.githubusercontent.com/5727373/69972642-e47d3d00-1519-11ea-836e-3335867fe9d3.jpeg)

**Comment by Trancever** [comment] 2019-12-12 15:25
Duplicate of #1375 .

**Closed by Trancever** 2019-12-12 15:25 UTC
