### ISSUE TITLE
Button roundness being ignored

### ISSUE THREAD

**Issue by jacquesdev** [callstack/react-native-paper#3939] opened 2023-06-16 13:15 UTC
### Current behaviour
Setting roundness seems to have no effect on a Button component

### Expected behaviour
Setting theme={{ roundness: 5 }} should set it to the custom value

### How to reproduce?
Setting `theme={{ roundness: 5 }}` at the component level, or passing this value in at the global theme level seems to have no effect.

I found it will change if I set it in the Button component `theme={{ isV3: false, roundness: 5 }}`. I'm not sure why I need to set it to false, seems like a bug to me? Adding isV3 in the global theme object does not make a difference unfortunately, and ideally I'd like to define it a the global theme level.

### Preview
v3 = not defined
<img width="172" alt="Screenshot 2023-06-16 at 14 12 48" src="https://github.com/callstack/react-native-paper/assets/7842197/82ab3669-2bbc-4fd7-8d0f-4daf96c34d19">
v3 = false
<img width="174" alt="Screenshot 2023-06-16 at 14 13 07" src="https://github.com/callstack/react-native-paper/assets/7842197/a5bdfa27-3545-45bf-921f-af015d10549f">

### What have you tried so far?
Playing around with the v3 version

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.71.8
| react-native-paper    | 5.8.0
| node                            | x.x.x
| npm or yarn                | npm
| expo sdk                     | 48.0.18

**Comment by lukewalczak** [comment] 2023-06-16 15:15
Hey @jacquesdev, I'm not able to reproduce the issue related to setting roundness in the `Button` component.

There are two ways to do that:

* use `style` property:

```
  <Button
    mode="contained-tonal"
    onPress={() => {}}
    style={{ borderRadius: 10 }}
  >
    Press
  </Button>
```

* override the `roundness` using `theme` prop:

```
  <Button
    mode="contained-tonal"
    onPress={() => {}}
    theme={{ roundness: 2 }}
  >
    Press
  </Button>
```

> I found it will change if I set it in the Button component theme={{ isV3: false, roundness: 5 }}. I'm not sure why I need to set it to false, seems like a bug to me? Adding isV3 in the global theme object does not make a difference unfortunately, and ideally I'd like to define it a the global theme level.

About the `isV3` property you can read more [there](https://callstack.github.io/react-native-paper/docs/guides/migration-guide-to-5.0#versioning)

**Comment by jacquesdev** [comment] 2023-06-16 22:08
Hi Luke!

Thanks, I'll try to recreate it when I get a second on a separate project. I can definitely use style that works fine - but when I use theme with roundness it seems to be happening.

**Comment by lukewalczak** [comment] 2023-06-17 13:21
Closing the issue, however, if you will be able to reproduce the issue, feel free to attach the repro and reopen it

**Closed by lukewalczak** 2023-06-17 13:21 UTC
Labels: bug, Button

**Comment by enzo-IFC** [comment] 2024-01-31 15:00
Did you fix it by any change ? Having the same issue

**Comment by jacquesdev** [comment] 2024-01-31 22:40
iirc I ended up setting the roundness in a separate style, not at the theme level

**Comment by fxricky** [comment] 2024-10-06 08:12
I'm facing the same issue now, setting the `roundness` at component level works fine.
However, when I try to apply `roundness` at the `theme` level, the `roundness` only works after applying `isV3 : false` 👀

**Comment by kferch-teamworks** [comment] 2024-11-06 20:25
Button border radius for v3 should use theme roundness but does not properly do so.
