### ISSUE TITLE
Theme not changing in example app

### ISSUE THREAD

**Issue by MatteoBuffo** [callstack/react-native-paper#3580] opened 2023-01-09 11:03 UTC
### Current behaviour

The example app theme does not match the system one: the light theme is always set. I'm testing it on two Android physical devices, but it works fine on Web and on the standalone Play Store app.

### Expected behaviour

The app theme should follow the system theme.

### How to reproduce?

[Example app](https://snack.expo.dev/@react-native-paper/react-native-paper-example_v5)

### What have you tried so far?

...

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | Both 9 and 12
| react-native                | x.x.x
| react-native-paper    | 5.1.2
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | 46.0.0

**Comment by lukewalczak** [comment] 2023-01-09 11:10
Hey @MatteoBuffo, it's not a bug. By default, Paper apps are always set to a `light` theme, which you can switch in the drawer. However if you will navigate directly into one of the  `Theme -> Themed Sport App` examples, then the theme is based on your system preferences.

**Comment by MatteoBuffo** [comment] 2023-01-09 11:17
@lukewalczak sorry, I forgot to mention that I'm checking the ThemeExample screen (the one containing the `Themed Sport App` section). If you move there and try to change the system theme, it won't change.

> By default, Paper apps are always set to a light theme, which you can switch in the drawer.

This applies to other screens, I guess.

**Comment by lukewalczak** [comment] 2023-01-09 11:20
@MatteoBuffo please check if your android device doesn't [force the dark theme](https://androidwaves.com/force-android-apps-to-use-dark-mode/#:~:text=Once%20developer%20options%20is%20turned,under%20%E2%80%9Csystems%20settings%E2%80%9D).&text=Step%204%3A%20Open%20systems%20settings,that%20do%20not%20support%20it)

**Comment by lukewalczak** [comment] 2023-01-09 11:29
Oh wait, prolly I missed that it happens only for the example app on the snack. I will check it.

**Comment by MatteoBuffo** [comment] 2023-01-09 11:34
Yep: as I wrote before, it only happens in the example app Snack.

**Comment by lukewalczak** [comment] 2023-01-09 11:50
Looks like we are not able to change it since according to the Expo [docs](https://docs.expo.dev/guides/color-schemes/#tips), snack is locked to `light` mode:

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/22746080/211301601-eda905f5-563a-432e-9440-6565d7325e2a.png">

**Comment by MatteoBuffo** [comment] 2023-01-09 11:53
Oh, got it. So I guess the only way to test it on a real device is to generate a build via Expo, install it on an Android device on try it, right?

**Comment by lukewalczak** [comment] 2023-01-09 12:02
> Oh, got it. So I guess the only way to test it on a real device is to generate a build via Expo, install it on an Android device on try it, right?

Yes, looks like there is a need to create a project which you can run on the device. Added info about locked mode into the example snack, hence closing the ticket.

**Closed by lukewalczak** 2023-01-09 12:02 UTC
Labels: bug, example app, Theme
