### ISSUE TITLE
Some components got warnings

### ISSUE THREAD

**Issue by mreorhan** [callstack/react-native-paper#1190] opened 2019-07-07 15:37 UTC
## Environment
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 4.10 GB / 15.89 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156

## Description
I got some warnings my rn project.
D:\XXX\node_modules\metro\src\lib\polyfills\require.js:114 
Require cycle: node_modules\react-native-paper\src\components\FAB\FAB.js -> node_modules\react-native-paper\src\components\FAB\FABGroup.js -> node_modules\react-native-paper\src\components\FAB\FAB.js
Require cycle: node_modules\react-native-paper\src\components\Appbar\Appbar.js -> node_modules\react-native-paper\src\components\Appbar\AppbarHeader.js -> node_modules\react-native-paper\src\components\Appbar\Appbar.js
Require cycle: node_modules\react-native-paper\src\components\ToggleButton\ToggleButton.js -> node_modules\react-native-paper\src\components\ToggleButton\ToggleButtonGroup.js -> node_modules\react-native-paper\src\components\ToggleButton\ToggleButton.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle

**Comment by iyadthayyil** [comment] 2019-07-07 16:18
I think this is fixed in #1172

**Comment by mreorhan** [comment] 2019-07-07 17:16
> I think this is fixed in #1172
Im currently using last version.
    "react": "16.8.3",
    "react-native": "0.59.6",
    "react-native-paper": "^2.16.0",

**Comment by muyaszed** [comment] 2019-07-12 19:04
I am having these warnings as well

**Comment by satya164** [comment] 2019-07-12 19:07
This is an unnecessary warning from metro: https://github.com/facebook/metro/issues/287

It's not a bug.

**Closed by satya164** 2019-07-12 19:07 UTC
