### ISSUE TITLE
Typescript Type Definitions

### ISSUE THREAD

**Issue by Kausta** [callstack/react-native-paper#505] opened 2018-08-26 10:46 UTC
### Current behaviour

There is no type definitions file `index.d.ts` shipping with react-native-paper, or no DefinitelyTyped module @types/react-native-paper. This causes TypeScript users to not have type checking for the react-native-paper library.

### Expected behaviour

As a popular library, I would expect the react-native-paper to have type definitions and can work on them if it is wanted by the community.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | *
| react-native          | *
| react-native-paper    | *
| node                  | *
| npm or yarn           | *

It would be nice if such a nice library had TypeScript type definitions, they also work for flow. I will start working on them when I find time, anybody can help if they want. It will be in the standard format other JS libraries create type definitions, a single .d.ts file containing all the components. 

Note: If the file is not wanted in the library, I can also submit it to DefinitelyTyped, however I think that small libraries containing their .d.ts file instead of having seperate @types/bla-bla libraries is much nicer and doesn't pollute package.json's as much.

**Comment by doomsower** [comment] 2018-08-26 13:35
Oh I totally forgot about that one.
So here is what I use now, maybe something is outdated, but it works for me. It's based on flow types, and I also checked sources to see which props are destructured and passed to native components.
https://gist.github.com/doomsower/4fe0d7d45e9b2b463377567ae89df1bc
I don't think I'm going to make it into PR though....

**Comment by Kausta** [comment] 2018-08-26 20:52
It looks nice, I can probably check whether it's consistent with current version and make it into a PR ( or a DefinitelyTyped library ). It's already pretty complete though.

**Comment by satya164** [comment] 2018-09-13 10:49
Duplicate of #306

**Closed by satya164** 2018-09-13 10:49 UTC
